### ISSUE TITLE
Fix Continuum calls in spectrum and radLoss, tests, and improve documentation

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#116]
#114 greatly improved the `Continuum` module, but broke compatibility with other modules that call it, including spectrum and radLoss. **Until these things are fixed, these modules will be broken and the tests will fail.** 

Also, the `Continuum` documentation needs improving. This issue is mostly so I don't forget to do these things. 

## TODO List
- [x] Add loss function methods for free-free, free-bound
- [x] Fix continuum tests
- [x] Fix other modules which use continuum module
- [x] Documentation

**Comment by kdere** [comment]
OK

**Comment by wtbarnes** [comment]
@kdere the previous version of the continuum module had free-free loss (`freeFreeLoss`) and free-bound loss (`freeBoundLoss`) methods. These are used in the `radLoss` module to calculate the free-free and free-bound contributions to the radiative loss function. 

Do you have a reference for what formulas are used to calculate these loss rates? Are these just the free-free and free-bound emission summed over wavelength? I've looked at both the IDL code and the old continuum methods and haven't been able to sort this out.

**Comment by kdere** [comment]
yes, they are just integrated/summed over wavelength, as I remember

**Comment by kdere** [comment]
also, there are new look-up tables for the free-bound loss rate, the ADS ref is:

http://adsabs.harvard.edu/abs/2017A%26A...599A..10M

we don't have this in Chianti yet but it should be there.

**Comment by wtbarnes** [comment]
Ok thanks. I've sorted out the free-free loss rate equation (it is actually in Rybicki & Lightman, Eq. 5.15a). The free-bound loss rate is a bit trickier, but I think I've figured it out from the Mewe et al. (1985) and Gronenschild and Mewe (1978) papers along with the CHIANTI IDL code.
